name: 'Build and Deploy'
description: 'Build a module docker image and deploy to k8s'
inputs:
  module:  # id of input
    description: 'module to deploy'
    required: true
    default: 'api'
  env:  # id of input
    description: 'env to deploy to'
    required: true
    default: 'dev'
  channel_id:  # id of input
    description: 'slack channel to notify'
    required: true
    default: 'dev'
  AWS_ACCESS_KEY_ID:  # id of input
    required: true
  AWS_SECRET_ACCESS_KEY:  # id of input
    required: true
  AWS_REGION:  # id of input
    required: true
  KUBECONFIG:  # id of input
    required: true
  RELEASE_TOKEN:  # id of input
    required: true
  SLACK_BOT_TOKEN:  # id of input
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: build
      shell: bash
      env:
        KUBE_CONFIG_DATA: ${{ inputs.KUBECONFIG }}
        GITHUB_TOKEN: ${{ inputs.RELEASE_TOKEN }}
      run: |
        ./bin/build-and-deploy-module.sh ${{ inputs.module }} ${{ inputs.env }}

    - name: Post to a Slack channel
      if: ${{ failure() }}
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ inputs.channel_id }}
        # For posting a simple plain text message
        slack-message: "Api build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
